default_language_version:
    python: python3.12  # substitua pela versão correta do Python no seu sistema

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.245
  hooks:
  - id: ruff
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
